name: docs-lint

on:
  pull_request:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with: 
          globs: |
            docs-chef-io/content/**/*.md
            !_vendor/
 
