name: docs-lint
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v5
      with: 
        config: "docs-chef-io/chef-web-docs/.markdownlint.yaml"
        globs: "docs-chef-io/content/workstation/*.md"
 
