name: docs-lint
on:
  pull_request:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-node@v2
      - run: npm install yaml
      - run: node --require yaml
      - run: npm install markdownlint-rule-titlecase
      - uses: carlosperate/download-file-action@v1
        with:
          file-url: "https://github.com/chef/chef-web-docs/blob/main/.markdownlint.yaml"
          file-name: ".markdownlint.yaml"
          location: "./docs-chef-io"
      - name: Check the file is there
        run: ls -l docs-chef-io/.markdownlint.yaml
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v5
        with: 
          globs: "docs-chef-io/content/**/*.md"
 
